# .github/dependabot.yml
# Configure Dependabot to keep dependencies up to date

version: 2
updates:
  # 1. Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"          # Location of workflow files
    schedule:
      interval: "weekly"
    # Optionally:
    # allow:
    #   - dependency-type: "direct"
    #   - dependency-type: "all"
    # commit-message:
    #   prefix: "chore(deps)"
  
  # 2. Update Python dependencies from requirements.txt
  - package-ecosystem: "pip"
    directory: "/"          # Root directory containing requirements.txt
    schedule:
      interval: "weekly"
    # Optionally:
    # allow:
    #   - dependency-type: "direct"
    #   - dependency-type: "all"
    # open-pull-requests-limit: 5

  # 3. (Optional) Update Docker base images in Dockerfile
  - package-ecosystem: "docker"
    directory: "/"          # Root directory containing Dockerfile
    schedule:
      interval: "weekly"
    # Optionally:
    # open-pull-requests-limit: 5
